### ISSUE TITLE
Crash to desktop

### ISSUE THREAD

**Issue by Titanblade828** [benbenlaw/skyopolis-5#29]
when i right click to open the simple storage inventory from simple storage. I get a crash to desktop. I'm on version 4.1 of the pack i have included the crash report hope this helps.
[crash-2023-02-22_23.01.32-client.txt](https://github.com/benbenlaw/skyopolis-5/files/10809068/crash-2023-02-22_23.01.32-client.txt)

---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 2/22/23, 11:01 PM
Description: Unexpected error

java.lang.NoClassDefFoundError: mezz/jei/Internal
	at com.lothrazar.storagenetwork.jei.JeiHooks.getJeiTextInternal(JeiHooks.java:51) ~[SimpleStorageNetwork-1.18.2-1.6.2.jar%23188!/:1.18.2-1.6.2] {re:classloading}
	at com.lothrazar.storagenetwork.jei.JeiHooks.getFilterText(JeiHooks.java:21) ~[SimpleStorageNetwork-1.18.2-1.6.2.jar%23188!/:1.18.2-1.6.2] {re:classloading}
	at com.lothrazar.storagenetwork.gui.NetworkWidget.initJei(NetworkWidget.java:197) ~[SimpleStorageNetwork-1.18.2-1.6.2.jar%23188!/:1.18.2-1.6.2] {re:classloading}
	at com.lothrazar.storagenetwork.gui.NetworkWidget.initSearchbar(NetworkWidget.java:190) ~[SimpleStorageNetwork-1.18.2-1.6.2.jar%23188!/:1.18.2-1.6.2] {re:classloading}
	at com.lothrazar.storagenetwork.block.inventory.ScreenNetworkInventory.m_7856_(ScreenNetworkInventory.java:76) ~[SimpleStorageNetwork-1.18.2-1.6.2.jar%23188!/:1.18.2-1.6.2] {re:classloading}
	at net.minecraft.client.gui.screens.Screen.m_6575_(Screen.java:423) ~[client-1.18.2-20220404.173914-srg.jar%23215!/:?]

**Comment by Gurkysword12** [comment]
What do you have connected to the network?

**Comment by Titanblade828** [comment]
the only thing attached to the network is a chest with a link cable the network Root and storage request Table. not crossing any chunk borders either also tried without having anything attached to the network just the root and request table and it still crashes. looking deeper into the crash log it mentions about jei Hooks

 A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.lothrazar.storagenetwork.jei.JeiHooks.getJeiTextInternal(JeiHooks.java:51) ~[SimpleStorageNetwork-1.18.2-1.6.2.jar%23188!/:1.18.2-1.6.2] {re:classloading}
	at com.lothrazar.storagenetwork.jei.JeiHooks.getFilterText(JeiHooks.java:21) ~[SimpleStorageNetwork-1.18.2-1.6.2.jar%23188!/:1.18.2-1.6.2] {re:classloading}
	at com.lothrazar.storagenetwork.gui.NetworkWidget.initJei(NetworkWidget.java:197) ~[SimpleStorageNetwork-1.18.2-1.6.2.jar%23188!/:1.18.2-1.6.2] {re:classloading}
	at com.lothrazar.storagenetwork.gui.NetworkWidget.initSearchbar(NetworkWidget.java:190) ~[SimpleStorageNetwork-1.18.2-1.6.2.jar%23188!/:1.18.2-1.6.2] {re:classloading}
	at com.lothrazar.storagenetwork.block.request.ScreenNetworkTable.m_7856_ hope this helps
