### ISSUE TITLE
Putting @SimpleStorageNetwork Storage Request Table into JEI Search Enabled crashes with NoClassDefFoundError: mezz/jei/Internal

### ISSUE THREAD

**Issue by BuddhaBuddy1** [benbenlaw/skyopolis-5#31]
Clicked the Mode button to JEI, it crashed. Now, just right-clicking on the Storage Request Table crashes.

Breaking and replacing the Storage Request Table resets the button and regains access.

Attempting to attach the crash report is failing. I'm pasting in the top of the original one.

> ---- Minecraft Crash Report ----
> // There are four lights!
> 
> Time: 3/7/23, 12:56 PM
> Description: charTyped event handler
> 
> java.lang.NoClassDefFoundError: mezz/jei/Internal
> 	at com.lothrazar.storagenetwork.jei.JeiHooks.setJeiTextInternal(JeiHooks.java:47) ~[SimpleStorageNetwork-1.18.2-1.6.2.jar%23188!/:1.18.2-1.6.2] {re:classloading}
> 	at com.lothrazar.storagenetwork.jei.JeiHooks.setFilterText(JeiHooks.java:38) ~[SimpleStorageNetwork-1.18.2-1.6.2.jar%23188!/:1.18.2-1.6.2] {re:classloading}
> 	at com.lothrazar.storagenetwork.gui.NetworkWidget.syncTextToJei(NetworkWidget.java:207) ~[SimpleStorageNetwork-1.18.2-1.6.2.jar%23188!/:1.18.2-1.6.2] {re:classloading}
> 	at com.lothrazar.storagenetwork.gui.NetworkWidget.charTyped(NetworkWidget.java:271) ~[SimpleStorageNetwork-1.18.2-1.6.2.jar%23188!/:1.18.2-1.6.2] {re:classloading}
> 	at com.lothrazar.storagenetwork.block.request.ScreenNetworkTable.m_5534_(ScreenNetworkTable.java:227) ~[SimpleStorageNetwork-1.18.2-1.6.2.jar%23188!/:1.18.2-1.6.2] {re:classloading}

**Comment by moody69420** [comment]
this is a known mod bug please report and add to their list.

**Comment by moody69420** [comment]
untill they fix it avoid jei mode in ssn
