### ISSUE TITLE
Pressing "U" on ender pouch crashes game

### ISSUE THREAD

**Issue by benbenlaw** [benbenlaw/skyopolis-5#8]
Thread: Render thread
Stacktrace:
	at java.util.Arrays$ArrayList.get(Arrays.java:4165) ~[?:?] {}
	at net.minecraft.core.NonNullList.get(NonNullList.java:47) ~[client-1.18.2-20220404.173914-srg.jar%23185!/:?] {re:mixin,re:classloading}
	at com.simibubi.create.compat.jei.category.MechanicalCraftingCategory.draw(MechanicalCraftingCategory.java:105) ~[create-mc1.18.2_v0.4.1.jar%2378!/:mc1.18.2_v0.4.1] {re:classloading}
	at com.simibubi.create.compat.jei.category.MechanicalCraftingCategory.draw(MechanicalCraftingCategory.java:32) ~[create-mc1.18.2_v0.4.1.jar%2378!/:mc1.18.2_v0.4.1] {re:classloading}
	at mezz.jei.api.recipe.category.IRecipeCategory.draw(IRecipeCategory.java:94) ~[jei-1.18.2-9.7.0.196.jar%23116!/:9.7.0.196] {re:classloading}
	at mezz.jei.gui.recipes.RecipeLayout.drawRecipe(RecipeLayout.java:167) ~[jei-1.18.2-9.7.0.196.jar%23116!/:9.7.0.196] {re:classloading,re:mixin}
	at mezz.jei.gui.recipes.RecipesGui.m_6305_(RecipesGui.java:245) ~[jei-1.18.2-9.7.0.196.jar%23116!/:9.7.0.196] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:386) ~[forge-1.18.2-40.1.48-universal.jar%23190!/:?] {re:mixin,re:classloading,pl:mixin:A}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:379) ~[forge-1.18.2-40.1.48-universal.jar%23190!/:?] {re:mixin,re:classloading,pl:mixin:A}
	
	
	possibly create and JEI?

**Comment by Gurkysword12** [comment]
still occurs wouldnt even know how to go about fixing this
